#!/usr/bin/env python3
"""Fail closed unless the checked-out authority tree matches its manifest."""

from __future__ import annotations

import re
import stat
from pathlib import Path

from common import load_json, read_bytes_once, sha256_bytes


ROOT = Path(__file__).resolve().parents[2]
DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")


def main() -> None:
    manifest_path = ROOT / "MANIFEST.json"
    manifest = load_json(manifest_path)
    declared: dict[str, str] = {}
    for item in manifest.get("files", []):
        path = item.get("path") if isinstance(item, dict) else None
        digest = item.get("sha256") if isinstance(item, dict) else None
        if (
            not isinstance(path, str)
            or not path
            or path.startswith("/")
            or ".." in Path(path).parts
            or not isinstance(digest, str)
            or DIGEST_RE.fullmatch(digest) is None
            or path in declared
        ):
            raise ValueError("authority manifest entry is malformed")
        declared[path] = digest

    observed: dict[str, str] = {}
    for path in sorted(ROOT.rglob("*")):
        if ".git" in path.parts or path == manifest_path:
            continue
        info = path.lstat()
        if stat.S_ISLNK(info.st_mode):
            raise ValueError("authority tree contains a symlink")
        if stat.S_ISDIR(info.st_mode):
            continue
        if not stat.S_ISREG(info.st_mode):
            raise ValueError("authority tree contains a non-regular public entry")
        relative = path.relative_to(ROOT).as_posix()
        if "__pycache__" in path.parts or path.suffix == ".pyc":
            raise ValueError("authority tree contains generated bytecode")
        observed[relative] = sha256_bytes(read_bytes_once(path))
    if observed != declared:
        raise ValueError("authority tree does not reconstruct from MANIFEST.json")


if __name__ == "__main__":
    main()
